version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/geostore-web
hooks:
  BeforeInstall:
    - location: scripts/start.sh
      timeout: 3
      runas: root
#   ApplicationStop:
#     - location: scripts/start.sh
#       timeout: 3000
#       runas: root

