version: 0.0
os: linux
files:
  - source: .
    destination: /geostore
hooks:
  BeforeInstall:
    - location: scripts/start
      timeout: 300
      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server
#      timeout: 300
#      runas: root
