version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/geostore-web
hooks:
  BeforeInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server
#      timeout: 300
#      runas: root
