version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/geostore-web
hooks:
 BeforeInstall:
   - location: scripts/stop.sh
     timeout: 300
     runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 3000
      runas: root

